name: SpaTrack
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - comm=0.2.2
  - debugpy=1.8.11
  - entrypoints=0.4
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - ipykernel=6.29.5
  - ipython=8.37.0
  - jedi=0.19.2
  - jupyter_client=7.3.4
  - jupyter_core=5.8.1
  - ld_impl_linux-64=2.40
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - matplotlib-inline=0.1.7
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - openssl=1.1.1w
  - packaging=25.0
  - parso=0.8.4
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=5.9.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.2.0
  - readline=8.2
  - setuptools=78.1.1
  - six=1.17.0
  - sqlite=3.45.3
  - stack_data=0.6.3
  - tk=8.6.14
  - tornado=6.1
  - traitlets=5.14.3
  - typing_extensions=4.14.0
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zlib=1.2.13
  - pip:
      - absl-py==2.3.1
      - addict==2.4.0
      - aiofiles==24.1.0
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.14
      - aiohttp-cors==0.8.1
      - aiosignal==1.4.0
      - albucore==0.0.24
      - albumentations==2.0.8
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.9.0
      - appdirs==1.4.4
      - astunparse==1.6.3
      - async-timeout==5.0.1
      - attrs==25.3.0
      - beautifulsoup4==4.13.4
      - cachetools==5.5.2
      - certifi==2022.12.7
      - charset-normalizer==2.1.1
      - click==8.2.1
      # - clip==1.0
      - git+https://github.com/openai/CLIP.git
      - colorful==0.5.7
      - contourpy==1.3.2
      - cupy==12.2.0
      - cycler==0.12.1
      - decorator==4.4.2
      - decord==0.6.0
      - defusedxml==0.7.1
      - distlib==0.3.9
      - easydict==1.13
      - einops==0.7.0
      - einx==0.3.0
      - fastapi==0.116.1
      - fastrlock==0.8.3
      - ffmpy==0.6.0
      - filelock==3.13.1
      - flatbuffers==25.9.23
      - flow-vis==0.1
      - fonttools==4.58.2
      - frozendict==2.4.6
      - frozenlist==1.7.0
      - fsspec==2024.6.1
      - ftfy==6.3.1
      - gast==0.6.0
      - gdown==5.2.0
      - glcontext==3.0.0
      - google-api-core==2.25.1
      - google-auth==2.40.3
      - google-pasta==0.2.0
      - googleapis-common-protos==1.70.0
      - gradio==5.31.0
      - gradio-client==1.10.1
      - groovy==0.1.2
      - grpcio==1.73.1
      - h11==0.16.0
      - h5py==3.14.0
      - hf-xet==1.1.5
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==0.33.4
      - hydra-core==1.3.2
      - idna==3.4
      - imageio==2.37.0
      - imageio-ffmpeg==0.6.0
      - importlib-metadata==8.7.0
      - jaxtyping==0.3.2
      - jinja2==3.1.4
      - joblib==1.5.1
      - jsonschema==4.24.0
      - jsonschema-specifications==2025.4.1
      - keras==3.11.3
      - kiwisolver==1.4.8
      - kornia==0.8.1
      - kornia-rs==0.1.9
      - lazy-loader==0.4
      - libclang==18.1.1
      - markdown==3.9
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.3
      - mdurl==0.1.2
      - mediapy==1.2.4
      - ml-dtypes==0.5.3
      - moderngl==5.12.0
      - moviepy==2.1.2
      - mpmath==1.3.0
      - msgpack==1.1.1
      - multidict==6.6.3
      - namex==0.1.0
      - narwhals==1.47.0
      - networkx==3.3
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.99
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencensus==0.11.4
      - opencensus-context==0.1.3
      - opencv-python==4.9.0.80
      - opencv-python-headless==4.12.0.88
      - opentelemetry-api==1.35.0
      - opentelemetry-exporter-prometheus==0.56b0
      - opentelemetry-proto==1.35.0
      - opentelemetry-sdk==1.35.0
      - opentelemetry-semantic-conventions==0.56b0
      - opt-einsum==3.4.0
      - optree==0.17.0
      - orjson==3.11.0
      - pako==0.3.1
      - pandas==2.3.1
      - pillow==10.4.0
      - pip==25.2
      - plotly==6.2.0
      - plyfile==1.1.2
      - prettytable==3.16.0
      - proglog==0.1.12
      - prometheus-client==0.22.1
      - propcache==0.3.2
      - proto-plus==1.26.1
      - protobuf==6.31.1
      - py-spy==0.4.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pyceres==2.4
      - pycocotools==2.0.10
      - pycolmap==3.11.1
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pyjwt==2.10.1
      - pyparsing==3.2.3
      - pysocks==1.7.1
      - python-dotenv==1.1.1
      - python-multipart==0.0.20
      - pytz==2025.2
      - pyyaml==6.0.2
      - ray==2.47.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.28.1
      - rich==14.0.0
      - rpds-py==0.26.0
      - rsa==4.9.1
      - ruff==0.12.3
      - safehttpx==0.1.6
      - safetensors==0.5.3
      - scikit-image==0.22.0
      - scikit-learn==1.7.0
      - scipy==1.15.3
      - segment-anything==1.0
      - semantic-version==2.10.0
      - shellingham==1.5.4
      - simsimd==6.5.0
      - smart-open==7.3.0.post1
      - sniffio==1.3.1
      - soupsieve==2.7
      - starlette==0.47.1
      - stringzilla==3.12.5
      - supervision==0.26.1
      - sympy==1.13.1
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tensorflow==2.20.0
      - termcolor==3.1.0
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==0.6.7
      - tokenizers==0.21.2
      - tomli==2.2.1
      - tomlkit==0.13.3
      - torch==2.5.1+cu121
      - torchaudio==2.5.1+cu121
      - torchvision==0.20.1+cu121
      - tqdm==4.67.1
      - transformers==4.53.2
      - trimesh==4.6.11
      - triton==3.1.0
      - typer==0.16.0
      - typing-extensions==4.12.2
      - tzdata==2025.2
      - urllib3==1.26.13
      - utils3d==0.0.2
      - uvicorn==0.35.0
      - virtualenv==20.31.2
      - wadler-lindig==0.1.7
      - websockets==15.0.1
      - werkzeug==3.1.3
      - wrapt==1.17.2
      - xformers==0.0.28
      - yapf==0.43.0
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /mnt/homes/jialin-ldap/miniconda3/envs/SpaTrack
